# Seth Elias
## Week 11 - 10/29/24
### Python Numpy Universal Functions

In [1]:
#universal functions are a powerful tool for performing mathematical operations on numpy arrays
import numpy as np
arr_1d = np.arange(21)
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr_1d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [3]:
arr_1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
# numpy.random.randn() function creates normally distributed array
arr_1d = np.random.randn(10)
arr_1d

array([-1.84730502, -0.79940841, -0.35916043,  1.39591721, -0.54260549,
       -0.44581597, -1.1041323 , -0.67240028, -1.80445509, -1.21385723])

In [5]:
arr_1d = np.random.randn(10)
arr_1d

array([ 0.40839099,  0.66091099,  0.13877042, -0.77305691, -1.52918608,
        0.9240939 , -0.5986121 , -0.05847064, -1.23296451,  1.11672003])

In [6]:
arr_2d = np.random.randn(4,5)
arr_2d

array([[-0.09552525, -0.67691813,  0.6017815 ,  1.23677383,  0.25875459],
       [ 0.29753959, -2.56214225, -1.20999737,  0.88569462,  1.34640425],
       [-0.5979361 ,  1.95959022, -0.95571025,  0.44889466, -0.72881154],
       [ 0.06117992,  1.95098285, -0.20719942, -0.33035974,  1.20305381]])

In [7]:
arr_3d = np.random.randn(4,5,2)
arr_3d

array([[[ 1.74370764,  0.47323883],
        [-0.69493989, -1.33722449],
        [ 0.24986569, -1.99668842],
        [-0.36770962,  0.17732601],
        [ 0.06633663,  2.68180585]],

       [[ 0.1024538 ,  0.62579201],
        [-0.44181198,  0.61200199],
        [-0.91685763,  2.33041129],
        [-0.55904644, -0.08452941],
        [ 2.27025825, -0.44871534]],

       [[-1.03535518, -0.79902246],
        [-0.02498347, -0.55311959],
        [ 1.01828332,  0.77817347],
        [-0.07222367,  1.01332279],
        [-0.45781634, -1.3849183 ]],

       [[ 0.19999352,  0.4110401 ],
        [ 0.44206026,  0.21496893],
        [ 1.27283489,  0.31552444],
        [-1.65783401,  0.18992878],
        [ 0.70053355,  0.15391374]]])

In [8]:
arr_1d

array([ 0.40839099,  0.66091099,  0.13877042, -0.77305691, -1.52918608,
        0.9240939 , -0.5986121 , -0.05847064, -1.23296451,  1.11672003])

In [9]:
arr_11d =  np.random.randn(10)
arr_11d

array([ 0.72841001, -0.13484049, -0.83628107,  0.23738488, -0.4526277 ,
       -0.33085218, -0.20695458, -0.39854548,  1.15423821,  1.17834987])

In [10]:
np.add(arr_1d,arr_11d)

array([ 1.13680101,  0.5260705 , -0.69751065, -0.53567203, -1.98181377,
        0.59324172, -0.80556668, -0.45701612, -0.0787263 ,  2.2950699 ])

In [11]:
#maximum
np.maximum(arr_1d,arr_11d)

array([ 0.72841001,  0.66091099,  0.13877042,  0.23738488, -0.4526277 ,
        0.9240939 , -0.20695458, -0.05847064,  1.15423821,  1.17834987])

In [12]:
np.minimum(arr_1d,arr_11d)

array([ 0.40839099, -0.13484049, -0.83628107, -0.77305691, -1.52918608,
       -0.33085218, -0.5986121 , -0.39854548, -1.23296451,  1.11672003])

In [13]:
arr_2d = np.ones(9).reshape(3,3)
arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
arr_1 = np.arange(9).reshape(3,3)

In [15]:
np.add(arr_1,arr_2d)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
# array filtering
arr_1 < 4

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [17]:
arr_2d <= 2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
arr_3d > 0

array([[[ True,  True],
        [False, False],
        [ True, False],
        [False,  True],
        [ True,  True]],

       [[ True,  True],
        [False,  True],
        [False,  True],
        [False, False],
        [ True, False]],

       [[False, False],
        [False, False],
        [ True,  True],
        [False,  True],
        [False, False]],

       [[ True,  True],
        [ True,  True],
        [ True,  True],
        [False,  True],
        [ True,  True]]])

In [19]:
#using where
#replace values of an array using where
from numpy.random import randn
arr = randn(3,3)
arr

array([[-0.01281121,  0.41248327, -0.35340909],
       [ 0.3738647 ,  0.00507441,  0.13956951],
       [ 0.2155712 ,  0.91359065,  0.28430701]])

In [20]:
np.where(arr<0,0,arr)# if smaller than zro, return zero, otherwise return original array value

array([[0.        , 0.41248327, 0.        ],
       [0.3738647 , 0.00507441, 0.13956951],
       [0.2155712 , 0.91359065, 0.28430701]])

In [21]:
np.where(arr<0,0,1)

array([[0, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [22]:
np.where([True,True,False],1,0)

array([1, 1, 0])

In [23]:
np.where(arr > -1, 1, 0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
np.where((arr < -.05) & (arr > 0),4,2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [25]:
arr = np.where([True, False, True],1,0)

In [26]:
arr

array([1, 0, 1])

In [27]:
# array for random sampling of true and fale values
sample = [True, False]
arr_bool = np.random.choice(sample, size=10)
arr_bool

array([False, False,  True, False, False, False, False,  True, False,
       False])

In [32]:
arr1 = np.arange(1,11)
arr2 = np.arange(1,11)*10

In [33]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr2

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
arr = np.where(arr_bool,arr1,arr2)
arr

array([ 10,  20,   3,  40,  50,  60,  70,   8,  90, 100])

In [36]:
arr

array([ 10,  20,   3,  40,  50,  60,  70,   8,  90, 100])

In [37]:
arr = [r1 if c else r2 for r1,r2,c in zip(arr1,arr2,arr_bool)]
arr

[10, 20, 3, 40, 50, 60, 70, 8, 90, 100]

In [38]:
list(zip(arr1,arr2,arr_bool))

[(1, 10, False),
 (2, 20, False),
 (3, 30, True),
 (4, 40, False),
 (5, 50, False),
 (6, 60, False),
 (7, 70, False),
 (8, 80, True),
 (9, 90, False),
 (10, 100, False)]

In [39]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [40]:
arr1

array([[1, 2],
       [3, 4]])

In [41]:
arr2

array([[5, 6],
       [7, 8]])

In [44]:
arr_bool = np.array([np.random.choice(sample, size = 2),np.random.choice(sample, size = 2 )])

In [45]:
arr_bool

array([[ True,  True],
       [False, False]])

In [46]:
arr_bool = np.random.choice(sample,size = 4).reshape(2,2)
arr_bool

array([[False,  True],
       [False,  True]])

In [47]:
arr = np.where(arr_bool,arr1,arr2)
arr

array([[5, 2],
       [7, 4]])

In [48]:
#all()
arr_bool = np.random.choice(sample, size = 5)
arr_bool

array([False,  True, False, False,  True])

In [49]:
arr_bool.all()

False

In [50]:
arr_bool = np.random.choice(sample, size = 5)
arr_bool

array([ True,  True, False,  True, False])

In [51]:
arr_bool.any()

True

In [53]:
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'])
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [54]:
np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [55]:
set(fruits)

{'Apple', 'Banana', 'Cherry', 'Orange'}

In [56]:
fruits

array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'],
      dtype='<U6')

In [57]:
'Apple' in set(fruits)

True

In [58]:
np.in1d(['Apple', 'Cherry', 'Grape'], fruits)

array([ True,  True, False])

In [59]:
#descriptive statisitcs
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.sum()

45

In [61]:
#axis0
arr.sum(0)

array([12, 15, 18])

In [62]:
arr.sum(1)

array([ 6, 15, 24])

In [63]:
np.sum(arr)

45

In [64]:
print(arr.mean(), ' ', arr.mean(0), ' ', arr.mean(1))

5.0   [4. 5. 6.]   [2. 5. 8.]


In [65]:
print(arr.std(), ' ', arr.std(0), ' ', arr.std(1))

2.581988897471611   [2.44948974 2.44948974 2.44948974]   [0.81649658 0.81649658 0.81649658]


In [66]:
# dot product of two arrays
arr1 = np.arange(5,20).reshape(3,5)
arr1

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
arr2 =  np.random.random((5,4))*10
arr2 = arr2.astype(int)

In [71]:
arr2

array([[5, 5, 4, 1],
       [5, 9, 6, 0],
       [7, 3, 2, 8],
       [1, 6, 1, 4],
       [5, 5, 7, 9]])

In [72]:
np.dot(arr1,arr2)

array([[157, 193, 141, 174],
       [272, 333, 241, 284],
       [387, 473, 341, 394]])

In [73]:
from numpy.random import randn, random

In [74]:
random((2,4))

array([[0.0464391 , 0.77458099, 0.23222586, 0.85650641],
       [0.03023391, 0.84129598, 0.14335551, 0.24284095]])

In [77]:
randn(3,3)

array([[-0.37613798,  0.577792  ,  1.01603656],
       [ 1.48729907,  1.42509355,  0.52991044],
       [-0.35581048,  0.52528795, -0.7901014 ]])

In [78]:
#joining numpy arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))

In [79]:
arr

array([1, 2, 3, 4, 5, 6])

In [80]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

In [81]:
arr1

array([[1, 2],
       [3, 4]])

In [82]:
arr2

array([[5, 6],
       [7, 8]])

In [83]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [84]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [85]:
arr = random(10) * 10
arr

array([3.63147139, 3.67179891, 3.1004169 , 5.00967981, 9.77590838,
       6.1066746 , 7.3480742 , 2.30448049, 6.01659784, 7.06029023])

In [86]:
np.array_split(arr,5)

[array([3.63147139, 3.67179891]),
 array([3.1004169 , 5.00967981]),
 array([9.77590838, 6.1066746 ]),
 array([7.3480742 , 2.30448049]),
 array([6.01659784, 7.06029023])]

In [90]:
#using numpy to find out higher scores in two exams
test1 = np.rint(random(50)*101)
test2 = np.rint(random(50)*101)

In [91]:
test1

array([ 87.,   1.,  73.,  95.,  44.,  91.,  12.,   3.,  75.,  94.,  58.,
        45., 100.,  62.,  19.,   4.,  81.,  89.,  28.,  60.,  69.,  91.,
        78.,  16.,  82.,  56.,  64.,  20.,  23.,  15.,  53.,  99.,  59.,
        19.,  74., 100.,  35.,  98.,  55.,  91.,  55.,  59.,   2.,  30.,
        74.,  47.,  52.,  92.,  74.,  11.])

In [92]:
test2

array([47., 93., 80., 87., 92., 55., 99., 86., 87., 22., 85., 57., 91.,
       26., 79.,  3., 67., 53., 10., 44., 51., 95., 18., 93.,  2., 96.,
        5., 70., 11., 60., 84., 14., 93., 76., 96., 36., 47., 71., 28.,
       87., 54., 81., 79., 62., 39., 13., 98., 55., 96., 44.])

In [93]:
test1.max()

100.0

In [94]:
test1.min()

1.0

In [95]:
test2.max()

99.0

In [96]:
test2.min()

2.0

In [97]:
np.maximum(test1,test2)

array([ 87.,  93.,  80.,  95.,  92.,  91.,  99.,  86.,  87.,  94.,  85.,
        57., 100.,  62.,  79.,   4.,  81.,  89.,  28.,  60.,  69.,  95.,
        78.,  93.,  82.,  96.,  64.,  70.,  23.,  60.,  84.,  99.,  93.,
        76.,  96., 100.,  47.,  98.,  55.,  91.,  55.,  81.,  79.,  62.,
        74.,  47.,  98.,  92.,  96.,  44.])

In [98]:
np.where(test1>test2,test1,test2)

array([ 87.,  93.,  80.,  95.,  92.,  91.,  99.,  86.,  87.,  94.,  85.,
        57., 100.,  62.,  79.,   4.,  81.,  89.,  28.,  60.,  69.,  95.,
        78.,  93.,  82.,  96.,  64.,  70.,  23.,  60.,  84.,  99.,  93.,
        76.,  96., 100.,  47.,  98.,  55.,  91.,  55.,  81.,  79.,  62.,
        74.,  47.,  98.,  92.,  96.,  44.])