# Seth Elias
## Week 12 - 11/05/24
### Numpy Real World Examples

In [6]:
# computing grades
import numpy as np
from numpy.random import random

scores = np.round(random(50)*101).astype(int)
scores

array([62,  4, 62, 50, 77, 62, 80, 62, 76, 52, 30, 88, 77, 25, 12, 27, 68,
       66, 99, 13, 45, 83, 80, 33, 77, 33, 66, 99, 46, 15, 57, 57, 84, 96,
        0, 36, 99, 66, 47, 64, 70, 85, 46, 78, 30, 13, 78,  4, 85, 89])

In [7]:
scores

array([62,  4, 62, 50, 77, 62, 80, 62, 76, 52, 30, 88, 77, 25, 12, 27, 68,
       66, 99, 13, 45, 83, 80, 33, 77, 33, 66, 99, 46, 15, 57, 57, 84, 96,
        0, 36, 99, 66, 47, 64, 70, 85, 46, 78, 30, 13, 78,  4, 85, 89])

In [8]:
np.mean(scores)

57.06

In [9]:
scores.min()

0

In [10]:
scores.max()

99

In [11]:
np.std(scores)

27.574198084441186

In [12]:
scores[scores > 70]

array([77, 80, 76, 88, 77, 99, 83, 80, 77, 99, 84, 96, 99, 85, 78, 78, 85,
       89])

In [13]:
len(scores[scores > 70])

18

In [15]:
# find n largest scores
n = 10
scores.sort()
scores[-n::]

array([83, 84, 85, 85, 88, 89, 96, 99, 99, 99])

In [16]:
# linear regression
x = np.array([1,2,3,4,5,6])
y = np.array([50,60,70,80,90,100])

slope, intercept = np.polyfit(x,y,1)

print(f'slope = {slope} and intercept = {intercept}')

slope = 9.999999999999996 and intercept = 39.999999999999986


In [18]:
# financial calculations
# future values of investments

initial_investment = 10000
interest_rate = 0.05
years = np.arange(1,11)
future_value = initial_investment * (1 + interest_rate) ** years
for year, value in zip(years, future_value):
    print(f'{year} {value:.2f}')

1 10500.00
2 11025.00
3 11576.25
4 12155.06
5 12762.82
6 13400.96
7 14071.00
8 14774.55
9 15513.28
10 16288.95


In [19]:
#portfolio optimization
returns = np.array([0.07, 0.05])
weights = np.array([0.6, 0.4])

portfolio_return = np.dot(returns,weights)

print(portfolio_return)

0.062000000000000006


In [21]:
#healthcare
# the effectiveness of a treatment by comparing patient outcomes

sample = [0,1]#1 = success 0 = failure

group_1 = np.random.choice(sample, 15)
print(group_1)

group_2 = np.random.choice(sample, 15)
print(group_2)

[0 1 0 0 0 1 0 1 0 0 1 1 0 0 0]
[1 0 0 0 0 0 1 0 1 1 1 0 0 0 1]


In [22]:
success_1 = np.mean(group_1)
success_2 = np.mean(group_2)

print(success_1, success_2)

0.3333333333333333 0.4


In [23]:
# scientific research
m = np.array([10.1, 10.5, 9.9, 10.3, 10.0])
mean = np.mean(m)
std = np.std(m)

print(mean, std)

10.16 0.2154065922853802


In [28]:
#image processing
#converting a color image to grayscale using python
import matplotlib.pyplot as plt
from PIL import Image

image = np.array(Image.open('C:/Users/andaconda/Downloads.python.jpg'))

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/andaconda/Downloads.python.jpg'

In [27]:
image

NameError: name 'image' is not defined