# Seth Elias
## Week 9 - 10/15/24
### Python numpy intro

-Numpy is a python librry
-Numpy is used for working with arrays
-Short for numerical python
-Arrays are frequently used in data science
-Speed and resources are very important
-50x faster than normal python lists

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# create a numpy ndarray object
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# dminesions in arrays
# a dimension in arrays is one level of array depth (nested arrays)
# nested array, arrays that have arrays as ther elements
# 0-D arrays, or scalars
arr_0d = np.array(50)
arr_0d

array(50)

In [9]:
arr_0d.ndim

0

In [10]:
type(arr_0d)

numpy.ndarray

In [11]:
#1-D array
#an array that has 0d arrays as it elements
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d, arr_1d.ndim)

[1 2 3 4 5 6] 1


In [15]:
#2d array
# array that has 1d arrays as it elements
arr_2d = np.array([[1,2,3,4,5,6], [7,8,9,10,12,13]])
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 12 13]]


In [16]:
arr_2d[0][2]

3

In [17]:
#3d array
# an array that has 2d array as its elements

In [21]:
arr_3d = np.array([ [ [1,2,3],[4,5,6] ], [ [7,8,9], [10,11,12] ]  ])

In [22]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
# create 4d array
arr_4d = np.array([1,2,3,4,5], ndim = 4)

TypeError: 'ndim' is an invalid keyword argument for array()

In [28]:
arr_3d.shape

(2, 2, 3)

In [29]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
# array indexing
arr_1d

array([1, 2, 3, 4, 5, 6])

In [31]:
arr_1d.shape

(6,)

In [32]:
arr_1d[-1]

6

In [33]:
arr_1d[0]

1

In [34]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 12, 13]])

In [35]:
arr_2d[1][5]

13

In [36]:
arr_2d.shape

(2, 6)

In [37]:
arr_2d[0][1]

2

In [38]:
arr_2d[0][1] = arr_2d[0][1] + 10

In [39]:
arr_2d

array([[ 1, 12,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 12, 13]])

In [40]:
arr_2d[1, 0] = arr_2d[1,0] + arr_2d[0, 0]

In [41]:
arr_2d

array([[ 1, 12,  3,  4,  5,  6],
       [ 8,  8,  9, 10, 12, 13]])