# Seth Elias
## Week 9 - 10/15/24
### Python numpy intro

-Numpy is a python librry
-Numpy is used for working with arrays
-Short for numerical python
-Arrays are frequently used in data science
-Speed and resources are very important
-50x faster than normal python lists

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# create a numpy ndarray object
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array((1,2,3,4,5,6,7,8,9,10))

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# dminesions in arrays
# a dimension in arrays is one level of array depth (nested arrays)
# nested array, arrays that have arrays as ther elements
# 0-D arrays, or scalars
arr_0d = np.array(50)
arr_0d

array(50)

In [9]:
arr_0d.ndim

0

In [10]:
type(arr_0d)

numpy.ndarray

In [11]:
#1-D array
#an array that has 0d arrays as it elements
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d, arr_1d.ndim)

[1 2 3 4 5 6] 1


In [12]:
#2d array
# array that has 1d arrays as it elements
arr_2d = np.array([[1,2,3,4,5,6], [7,8,9,10,12,13]])
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 12 13]]


In [13]:
arr_2d[0][2]

3

In [14]:
#3d array
# an array that has 2d array as its elements

In [15]:
arr_3d = np.array([ [ [1,2,3],[4,5,6] ], [ [7,8,9], [10,11,12] ]  ])

In [16]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
# create 4d array
arr_4d = np.array([1,2,3,4,5], ndim = 4)

TypeError: 'ndim' is an invalid keyword argument for array()

In [ ]:
arr_3d.shape

In [ ]:
arr_3d

In [ ]:
# array indexing
arr_1d

In [ ]:
arr_1d.shape

In [ ]:
arr_1d[-1]

In [ ]:
arr_1d[0]

In [ ]:
arr_2d

In [ ]:
arr_2d[1][5]

In [ ]:
arr_2d.shape

In [ ]:
arr_2d[0][1]

In [ ]:
arr_2d[0][1] = arr_2d[0][1] + 10

In [ ]:
arr_2d

In [ ]:
arr_2d[1, 0] = arr_2d[1,0] + arr_2d[0, 0]

In [ ]:
arr_2d

In [18]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
len(arr_3d)

2

In [20]:
arr_3d.shape

(2, 2, 3)

In [21]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr_3d[0][0][1]

2

In [23]:
arr_3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [24]:
arr_3d[1,1,1]

11

In [25]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr_3d[1,0,2]

9

In [27]:
#slicing np arrays

In [28]:
#[start:end:stop] start is default 0, end index is exclusive, step is default 1

In [29]:
arr_1d

array([1, 2, 3, 4, 5, 6])

In [30]:
arr_1d.shape

(6,)

In [31]:
arr_1d[1]

2

In [32]:
arr_1d[0:3]

array([1, 2, 3])

In [33]:
arr_1d[-3:]

array([4, 5, 6])

In [34]:
arr_1d[-3:-1]

array([4, 5])

In [35]:
arr_1d[::2]

array([1, 3, 5])

In [36]:
#slicing 2d arrays

In [37]:
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 12, 13]])

In [38]:
arr_2d.shape

(2, 6)

In [39]:
#start:stop:step two times
arr_2d[1]

array([ 7,  8,  9, 10, 12, 13])

In [40]:
arr_2d[:2]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 12, 13]])

In [41]:
arr_2d[0, 1:3]

array([2, 3])

In [42]:
arr_2d[1, -2:]

array([12, 13])

In [43]:
arr_2d[:,-2:]

array([[ 5,  6],
       [12, 13]])

In [44]:
arr_2d[:,:3]

array([[1, 2, 3],
       [7, 8, 9]])

In [46]:
#3d arrays
#start:stop:step 3 times
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr_3d.shape

(2, 2, 3)

In [48]:
arr_3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr_3d[0:1]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [50]:
arr_3d[:,0]

array([[1, 2, 3],
       [7, 8, 9]])

In [51]:
arr_3d[:,0,-2:]

array([[2, 3],
       [8, 9]])

In [52]:
arr_3d[:,1,:2]

array([[ 4,  5],
       [10, 11]])

In [53]:
arr_3d[:,1,0:2]

array([[ 4,  5],
       [10, 11]])

In [54]:
#different data elements dims
arr_d = np.array([ [[1,2],[3.4]] , [[5,6,7],[8,9,10]]    ])

In [55]:
arr_d

array([[list([1, 2]), list([3.4])],
       [list([5, 6, 7]), list([8, 9, 10])]], dtype=object)

In [56]:
arr_d.ndim

2

In [57]:
arr_d.shape

(2, 2)

In [58]:
arr_d = np.array([ [[1,2],[3.4]] , [[5,6],[8,9]]    ])

In [59]:
arr_d

array([[list([1, 2]), list([3.4])],
       [list([5, 6]), list([8, 9])]], dtype=object)