# Seth Elias
## Week 10 10/24/24 - 10/29/24
### Python numpy, processing, creating, transporting arrays

In [1]:
import numpy as np
# zeros
arr_1d = np.zeros(10)
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr_2d = np.zeros((5,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
arr_1d + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
arr_2d + 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [5]:
arr = np.ones((5,5))

In [6]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
arr = np.ones((5,5,2))

In [8]:
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
arr.shape

(5, 5, 2)

In [10]:
arr * .5

array([[[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]]])

In [11]:
arr = np.empty((5,5))

In [12]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
arr = np.arange(10, 101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
#reshape an array
#reshape 1d to 2d
arr_1d = np.arange(1,13,1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
arr_2d = arr_1d.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
arr_2d = arr_1d.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr_1d[:4]= [0,0,0,0]
arr_1d

array([ 0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
arr_2d = np.arange(1,13,1).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr_3d = np.arange(1,13,1).reshape(3,2,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
arr_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
#iterating 1-d
for n in arr_1d:
    print(n)

0
0
0
0
5
6
7
8
9
10
11
12


In [22]:
arr = [n*2 for n in arr_1d]

In [23]:
arr

[0, 0, 0, 0, 10, 12, 14, 16, 18, 20, 22, 24]

In [24]:
for n in arr_2d:
    print(n)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [25]:
#2-d iterations
for n in arr_2d:
    for num in n:
        print(num, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [26]:
#iterating 3-d arrays
for n in arr_3d:
    for num in n:
        for nums in num:
            print(nums, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [27]:
#nditer iterates on each scalar element in the np array
for n in np.nditer(arr_3d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [28]:
#multidimensional index iterator
# ndenumerate()
for i, n in np.ndenumerate(arr_1d):
    print(i, n)

(0,) 0
(1,) 0
(2,) 0
(3,) 0
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [29]:
for i, n in np.ndenumerate(arr_2d):
    print(i, n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [30]:
for i, n in np.ndenumerate(arr_3d):
    print(i, n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 0, 0) 9
(2, 0, 1) 10
(2, 1, 0) 11
(2, 1, 1) 12


In [31]:
#operations *,-,+,/
arr_2d = np.arange(1,9).reshape(4,2)

In [32]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
arr_2d.shape

(4, 2)

In [34]:
arr_2d * arr_2d

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]])

In [35]:
arr_2d + arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [36]:
arr_2d - arr_2d

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [37]:
arr_2d**2

array([[ 1,  4],
       [ 9, 16],
       [25, 36],
       [49, 64]], dtype=int32)

In [38]:
arr_2d * .5

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ],
       [3.5, 4. ]])

In [39]:
arr_2d**3

array([[  1,   8],
       [ 27,  64],
       [125, 216],
       [343, 512]], dtype=int32)

In [40]:
# .T or self.transpose()
# returns the transpose of the matrix
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr_1d.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr_2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
arr_2d.shape

(4, 2)

In [44]:
arr_2d.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [45]:
arr_2d = np.arange(45).reshape(9,5)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [47]:
arr_2d.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [48]:
arr_t = arr_2d.T

In [49]:
arr_t

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44]])

In [50]:
arr_2d[0] = 100

In [51]:
arr_2d

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44]])

In [52]:
arr_t

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [53]:
arr_t.shape

(5, 9)

In [54]:
arr_3d = np.arange(1,21).reshape(-1,5,4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]])

In [55]:
arr_3d.shape

(1, 5, 4)

In [56]:
arr_3d.T

array([[[ 1],
        [ 5],
        [ 9],
        [13],
        [17]],

       [[ 2],
        [ 6],
        [10],
        [14],
        [18]],

       [[ 3],
        [ 7],
        [11],
        [15],
        [19]],

       [[ 4],
        [ 8],
        [12],
        [16],
        [20]]])

In [57]:
arr_2d

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44]])

In [58]:
arr_2d.T

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [59]:
arr_2d.transpose()

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [60]:
arr_2d.transpose(0,1)

array([[100, 100, 100, 100, 100],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44]])

In [62]:
arr_2d.transpose(1,0) # changes rows with column, axis0 with axis1

array([[100,   5,  10,  15,  20,  25,  30,  35,  40],
       [100,   6,  11,  16,  21,  26,  31,  36,  41],
       [100,   7,  12,  17,  22,  27,  32,  37,  42],
       [100,   8,  13,  18,  23,  28,  33,  38,  43],
       [100,   9,  14,  19,  24,  29,  34,  39,  44]])

In [63]:
arr_2d.shape

(9, 5)

In [64]:
arr_3d = np.arange(20).reshape(2,5,2)
arr_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [65]:
arr_3d.T

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [66]:
arr_3d.T.shape

(2, 5, 2)

In [67]:
arr_3d.transpose()

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [68]:
arr_3d.transpose().shape

(2, 5, 2)

In [69]:
arr_3d.transpose(0,1,2)#no change in axis, same order

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [70]:
arr_3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [71]:
arr_3d.transpose(1,0,2).shape

(5, 2, 2)

In [72]:
arr_3d.transpose(0,2,1)

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [73]:
arr_t = arr_3d.transpose(0,2,1)

In [74]:
arr_t

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]]])

In [75]:
#swap axes
arr_1d = np.arange(5,16,5)
arr_1d

array([ 5, 10, 15])

In [76]:
arr_2d = arr_1d.reshape(1,3)
arr_2d

array([[ 5, 10, 15]])

In [77]:
arr_2d.swapaxes(0,1)

array([[ 5],
       [10],
       [15]])

In [78]:
arr_3d = np.arange(45).reshape(3,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [79]:
arr_3d.shape

(3, 5, 3)

In [80]:
arr_3d.swapaxes(1,2)

array([[[ 0,  3,  6,  9, 12],
        [ 1,  4,  7, 10, 13],
        [ 2,  5,  8, 11, 14]],

       [[15, 18, 21, 24, 27],
        [16, 19, 22, 25, 28],
        [17, 20, 23, 26, 29]],

       [[30, 33, 36, 39, 42],
        [31, 34, 37, 40, 43],
        [32, 35, 38, 41, 44]]])