# Seth Elias
## Week 10 10/24/24
### Python numpy, processing, creating, transporting arrays

In [1]:
import numpy as np
# zeros
arr_1d = np.zeros(10)
arr_1d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
arr_2d = np.zeros((5,10))
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
arr_1d + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
arr_2d + 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [5]:
arr = np.ones((5,5))

In [6]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
arr = np.ones((5,5,2))

In [8]:
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
arr.shape

(5, 5, 2)

In [10]:
arr * .5

array([[[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]],

       [[0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5],
        [0.5, 0.5]]])

In [11]:
arr = np.empty((5,5))

In [12]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
arr = np.arange(10, 101, 10)
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
#reshape an array
#reshape 1d to 2d
arr_1d = np.arange(1,13,1)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
arr_2d = arr_1d.reshape(2,6)
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
arr_2d = arr_1d.reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr_1d[:4]= [0,0,0,0]
arr_1d

array([ 0,  0,  0,  0,  5,  6,  7,  8,  9, 10, 11, 12])

In [19]:
arr_2d = np.arange(1,13,1).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr_3d = np.arange(1,13,1).reshape(3,2,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
arr_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
#iterating 1-d
for n in arr_1d:
    print(n)

0
0
0
0
5
6
7
8
9
10
11
12


In [23]:
arr = [n*2 for n in arr_1d]

In [24]:
arr

[0, 0, 0, 0, 10, 12, 14, 16, 18, 20, 22, 24]

In [25]:
for n in arr_2d:
    print(n)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [26]:
#2-d iterations
for n in arr_2d:
    for num in n:
        print(num, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [29]:
#iterating 3-d arrays
for n in arr_3d:
    for num in n:
        for nums in num:
            print(nums, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [30]:
#nditer iterates on each scalar element in the np array
for n in np.nditer(arr_3d):
    print(n, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [31]:
#multidimensional index iterator
# ndenumerate()
for i, n in np.ndenumerate(arr_1d):
    print(i, n)

(0,) 0
(1,) 0
(2,) 0
(3,) 0
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 10
(10,) 11
(11,) 12


In [32]:
for i, n in np.ndenumerate(arr_2d):
    print(i, n)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [33]:
for i, n in np.ndenumerate(arr_3d):
    print(i, n)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 0, 0) 9
(2, 0, 1) 10
(2, 1, 0) 11
(2, 1, 1) 12
