# Seth Elias
## Week 10 - 10/22/24 - 10/24/24
### Python Numpy - Processing Arrays

In [4]:
import numpy as np

In [5]:
lst = list(range(1,6))
lst2 = list(range(6,11))

In [6]:
lst1

NameError: name 'lst1' is not defined

In [7]:
lst

[1, 2, 3, 4, 5]

In [8]:
lst2

[6, 7, 8, 9, 10]

In [9]:
lst1 = [lst,lst2]

In [10]:
lst1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [11]:
arr_2d = np.array(lst1)

In [12]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr_2d.dtype

dtype('int32')

In [14]:
arr_1d = np.array(['Orange', 'Apple', 'Cherry', 'Grape'])

In [15]:
arr_1d

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [16]:
arr_1d.dtype

dtype('<U6')

In [17]:
# cpnvert data types
arr = np.array([10,11,12,13,14,15], dtype = 'S')

In [18]:
arr

array([b'10', b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [19]:
print(arr)

[b'10' b'11' b'12' b'13' b'14' b'15']


In [20]:
arr = np.array(list(range(1,6)), dtype = 'i4')

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr = np.array(list(range(5,11)), dtype = 'i8')
arr

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [23]:
arr.dtype

dtype('int64')

In [24]:
#converting data type on existing arrays
arr = np.array([78.5,88.9,90.3,89.9,87.6])

In [25]:
arr.dtype

dtype('float64')

In [26]:
#astype()
arr_int = arr.astype('i')

In [27]:
arr_int

array([78, 88, 90, 89, 87], dtype=int32)

In [28]:
arr

array([78.5, 88.9, 90.3, 89.9, 87.6])

In [29]:
arr = np.array([1,0,2,3,1,0,0,2])

In [30]:
arr

array([1, 0, 2, 3, 1, 0, 0, 2])

In [31]:
arr_b = arr.astype('bool')

In [32]:
arr_b

array([ True, False,  True,  True,  True, False, False,  True])

In [33]:
#numpy array copy vs view
'''
The differemce between copy and view
copy is a new array, view is just a view of the orginal array

'''

'\nThe differemce between copy and view\ncopy is a new array, view is just a view of the orginal array\n\n'

In [34]:
arr = np.array(list(range(10,16)))

In [35]:
arr

array([10, 11, 12, 13, 14, 15])

In [36]:
arr2 = arr
arr2

array([10, 11, 12, 13, 14, 15])

In [37]:
#both reference the same array

In [39]:
arr[:3] = [1, 2, 3]

In [40]:
arr

array([ 1,  2,  3, 13, 14, 15])

In [41]:
arr2

array([ 1,  2,  3, 13, 14, 15])

In [44]:
arr2_copy = arr.copy() #the copy is a new array

In [45]:
arr2_copy

array([ 1,  2,  3, 13, 14, 15])

In [46]:
arr[:3] = [11, 22, 33]

In [47]:
arr

array([11, 22, 33, 13, 14, 15])

In [48]:
arr2_copy

array([ 1,  2,  3, 13, 14, 15])

In [49]:
arr2_view = arr.view() #a view of the original array

In [50]:
arr2_view

array([11, 22, 33, 13, 14, 15])

In [51]:
arr[-3:] = [0, 1, 2]

In [52]:
arr

array([11, 22, 33,  0,  1,  2])

In [53]:
arr2_view

array([11, 22, 33,  0,  1,  2])

In [54]:
print(arr2_copy.base)

None


In [55]:
arr = np.array([list(range(1,6)), list(range(6,11))])

In [56]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
arr.shape

(2, 5)

In [58]:
#stacking, several arrays can be stacked together along different axes
#np.vstack to stack arrays along a vertical axis
#np.hstack to stack arrays along horizontal axis
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b

array([[5, 6],
       [7, 8]])

In [61]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [62]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [63]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
f = open('data.txt', 'w')
f.write('1, 2, 3\n')
f.write('4, 5, 6')
f.close()

In [65]:
#read data
f = open('data.txt', 'r')
print(f.read())

1, 2, 3
4, 5, 6


In [66]:
#using np.genfromtxt
arr = np.genfromtxt('data.txt', dtype=None, delimiter=',')

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr.ndim

2

In [69]:
arr.shape

(2, 3)

In [70]:
#using np.loadtxt
arr = np.loadtxt('data.txt', dtype='i', delimiter = ',')

In [71]:
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)